apiVersion: v1
kind: ConfigMap
metadata:
  name: migration-sql
  labels:
    app.kubernetes.io/name: migration-sql
    app.kubernetes.io/managed-by: Helm
data:
{{- range $path, $_ := .Files.Glob "migrations/*.sql" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}
