apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-microservice
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: oauth-microservice
  template:
    metadata:
      labels:
        app: oauth-microservice
    spec:
      containers:
        - name: oauth-microservice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db }}
            - name: POSTGRES_HOST
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: oauth-microservice
spec:
  selector:
    app: oauth-microservice
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
