replicaCount: 1

image:
  repository: oauth-microservice-user-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

postgres:
  username: authuser
  password: changeme123
  db: authdb
  host: postgres
  port: 5432