apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.service.port }}
        env:
          - name: POSTGRES_USER
            value: {{ .Values.postgres.username }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: user-service-postgres-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            value: {{ .Values.postgres.db }}
          - name: POSTGRES_HOST
            value: {{ .Values.postgres.host }}
          - name: POSTGRES_PORT
            value: {{ .Values.postgres.port | quote }}
