apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrations-{{ .Release.Revision }}
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-db
          image: postgres:14-alpine
          command: ["sh", "-c"]
          args:
            - |
              until pg_isready -h postgres -p 5432 -U postgres; do
                echo "Waiting for Postgres..."
                sleep 2
              done
      containers:
        - name: migrate
          image: migrate/migrate:v4.15.2
          command: ["sh", "-c"]
          args:
            - |
              echo "Running migrations..."
              migrate -path=/migration-scripts \
                -database postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.db }}?sslmode=disable up
          volumeMounts:
            - name: migration-scripts
              mountPath: /migration-scripts
      volumes:
        - name: migration-scripts
          configMap:
            name: migration-sql
